version: "3"

services:

  gotify:
    image: gotify/server
    ports:
      - 28080:80
    environment:
      - GOTIFY_DEFAULTUSER_PASS=custom
    volumes:
      - gotify_data:/app/data

volumes:
  gotify_data:
